[[plugins]]
package = "netlify-plugin-save-build-artifacts-s3"

[[redirects]]
  from = "/api/*"
  to = "https://test--promote-builds-api.netlify.app/.netlify/functions/api/:splat"
  status = 200
  force = true